### ISSUE TITLE
avoid the black space at the left

### ISSUE THREAD

**Issue by p-m** [dashpay/wp-dash-theme#168]
At line 454 in dash.css: 50% would be probably better than 53%.

**Comment by Silvanasss** [comment]
sorry but no, this is exactly like it should look like,  referring to a design

**Comment by p-m** [comment]
Ok. My eyes are probably too much accustomed to symmetry... ;)

**Comment by Silvanasss** [comment]
Now I've got what you mean, you referred to the background mask which has a
position absolute and can't move things around, and after some look around
I understood that you were talking about a space between neon lines, I
fixed it, thank you
Not live yet.

пт, 19 лип. 2024 р. о 16:09 p-m ***@***.***> пише:
